### ISSUE TITLE
Hacktoberfest welcome

### ISSUE THREAD

**Issue by MrNaif2018** [bitcartcc/bitcart-admin#10]
Main welcome: bitcartcc/bitcart#133

Issue list:
- [x] Fix favicon barely visible in darkmode (#7)
- [ ] Making all admin pages responsive (#11)
- [x] Set up formatting guidelines (prettier) (#13)

**Comment by arynn-gupta** [comment]
Would definitely like to fix this issue !

**Comment by MrNaif2018** [comment]
Thanks to everyone who has contributed to BitcartCC this hacktoberfest!
